[comment]
enable = true
provider= "giscus"

[comments.giscus]
lang = "zh-CN"
repo="erroreutopia/erroreutopia.github.io"
repoID="R_kgDOJ6q4wQ"
category="Announcements"
categoryID="DIC_kwDOJ6q4wc4CqLyJ"
mapping="pathname"
strict=0
lightTheme="preferred_color_scheme"
darkTheme="preferred_color_scheme"
reactionsEnabled= 1
emitMetadata= 0
inputPosition="bottom"